const pairs = [
{ key:"hallo/hi ", value:" hi"},
{ key:"hallo ", value:" hello"},
{ key:"willkommen ", value:" welcome "},
{ key:"danke ", value:" thanks "},
{ key:"dass ", value:" that, which "},
{ key:"zu ", value:" to"},
{ key:"über/in/ob ", value:" about, in, if "},
{ key:"in den Morgenstunden ", value:" in the mornings"},
{ key:"im Sommer ", value:" in the summer"},
{ key:"ungefähr ", value:" around "},
{ key:"der/das ", value:" that "},
{ key:"dieser/dieses ", value:" this "},
{ key:"diese ", value:" these "},
{ key:"haben ", value:" to have "},
{ key:"tschüss ", value:" bye"},
{ key:"auf Wiedersehen ", value:" goodbye"},
{ key:"viel Spaß! ", value:" have fun!"},
{ key:"hatten ", value:" had"},
{ key:"schön dich wiederzusehen ", value:" good to see you again"},
{ key:"gehen ", value:" to go, walk "},
{ key:"gegangen ", value:" gone "},
{ key:"gehen/zu gehen ", value:" go"},
{ key:"gingen ", value:" went, left"},
{ key:"ging ", value:" went"},
{ key:"dann ", value:" then, when "},
{ key:"tut mir leid ", value:" sorry "},
{ key:"entschuldigung ", value:" excuse me, sorry"},
{ key:"eine Entschuldigung/die Entschuldigung ", value:" the excuse, apology"},
{ key:"sehr ", value:" very "},
{ key:"viel ", value:" much, a lot"},
{ key:"viele ", value:" many, a lot "},
{ key:"mehrere ", value:" several"},
{ key:"wo ", value:" where, how "},
{ key:"was ", value:" what "},
{ key:"was auch immer ", value:" whatever, that which"},
{ key:"welche/welches/welcher ", value:" which"},
{ key:"wer ", value:" who "},
{ key:"wessen ", value:" whose "},
{ key:"wie viel ", value:" how much"},
{ key:"wie viele ", value:" how many"},
{ key:"wie alt ", value:" how old"},
{ key:"wie ", value:" how"},
{ key:"warum ", value:" why"},
{ key:"jeder/jedes ", value:" every, each "},
{ key:"wenn ", value:" if"},
{ key:"wann ", value:" when"},
{ key:"kosten ", value:" to cost"},
{ key:"kostete ", value:" cost "},
{ key:"heißen ", value:" are called "},
{ key:"hieß ", value:" was called"},
{ key:"hier ", value:" here"},
{ key:"da ", value:" there "},
{ key:"mehr ", value:" more"},
{ key:"mit ", value:" with "},
{ key:"aber ", value:" but"},
{ key:"nicht ", value:" not "},
{ key:"auch ", value:" also"},
{ key:"lustig/lustige ", value:" funny "},
{ key:"Spaß ", value:" fun"},
{ key:"nur ", value:" only"},
{ key:"gerne geschehen ", value:" youre welcome "},
{ key:"angenehm ", value:" pleasant, pleasure, nice "},
{ key:"bitte ", value:" please"},
{ key:"hier bitte ", value:" here you go"},
{ key:"sein ", value:" to be"},
{ key:"war ", value:" was"},
{ key:"vielleicht ", value:" maybe"},
{ key:"ein Wochenende/das Wochenende ", value:" the weekend "},
{ key:"gut/gutes/gute ", value:" good "},
{ key:"besser ", value:" better "},
{ key:"am besten ", value:" best "},
{ key:"als ", value:" than "},
{ key:"der Käse/Käse ", value:" the cheese"},
{ key:"der Fisch/die Fische (pl) ", value:" the fish"},
{ key:"das Essen/Essen ", value:" the food"},
{ key:"machen/zu machen ", value:" to make"},
{ key:"gemacht ", value:" made"},
{ key:"kochen ", value:" to cook"},
{ key:"gekocht ", value:" cooked "},
{ key:"kochte ", value:" cooked "},
{ key:"eine Mannschaft/die Mannschaft ", value:" the team"},
{ key:"die Gitarre/die Gitarren (pl) ", value:" the guitar"},
{ key:"spielen/zu spielen ", value:" to play "},
{ key:"spielte ", value:" played"},
{ key:"das Spiel/die Spiele (pl) ", value:" the game "},
{ key:"hören/zu hören ", value:" to hear, listen "},
{ key:"klingt ", value:" sounds "},
{ key:"gehört ", value:" heard "},
{ key:"hörte ", value:" heard "},
{ key:"hören/zu hören ", value:" to hear, listen "},
{ key:"der Klang/die Klänge (pl) ", value:" sound"},
{ key:"die Rechnung/die Rechnungen (pl) ", value:" the bill, account"},
{ key:"der Kellner/die Kellner (pl) ", value:" the waiter "},
{ key:"sehen/zu sehen ", value:" to see "},
{ key:"sieht aus ", value:" looks, sieht traurig aus -- she looks sad"},
{ key:"freuen sich ", value:" look forwards"},
{ key:"sah ", value:" saw "},
{ key:"freute sich ", value:" was looking forwards"},
{ key:"gesehen ", value:" seen "},
{ key:"der Arzt/die Ärzte (pl) ", value:" the doctor "},
{ key:"der Zahnarzt/die Zahnärzte (pl) ", value:" the dentist"},
{ key:"der Markt/die Märkte (pl) ", value:" the market"},
{ key:"der Professor/die Professoren (pl) ", value:" the professor"},
{ key:"krank/krank ", value:" sick "},
{ key:"Krankheit ", value:" sickness"},
{ key:"die Krankenschwester/die Krankenschwestern (pl) ", value:" the nurse"},
{ key:"das Krankenhaus/die Krankenhäuser (pl) ", value:" the hospital"},
{ key:"die Pille/die Pillen (pl) ", value:" the pill"},
{ key:"nett/nett/nette ", value:" kind, nice "},
{ key:"netter ", value:" kinder"},
{ key:"am nettesten ", value:" the kindest"},
{ key:"klug ", value:" smart"},
{ key:"stressig ", value:" stressful"},
{ key:"Stress ", value:" the stress "},
{ key:"stressen ", value:" to stress"},
{ key:"gestresst ", value:" stressed"},
{ key:"schwierig/schwierige ", value:" difficult"},
{ key:"leicht ", value:" easy, light "},
{ key:"leichter ", value:" easier"},
{ key:"interessant ", value:" interesting"},
{ key:"der Job/die Jobs (pl) ", value:" the job"},
{ key:"arbeiten/zu arbeiten ", value:" to work "},
{ key:"gearbeitet ", value:" worked"},
{ key:"funktionierte ", value:" worked "},
{ key:"warm/warm ", value:" warm"},
{ key:"wärmer ", value:" warmer, hotter"},
{ key:"kalt ", value:" cold"},
{ key:"hoch/hoch/hohe ", value:" tall, high, loud "},
{ key:"hoch ", value:" highly, loudly"},
{ key:"höher ", value:" higher, taller"},
{ key:"am höchsten ", value:" highest, loudest"},
{ key:"rechts ", value:" right "},
{ key:"links ", value:" left "},
{ key:"trinken/zu trinken ", value:" to drink, drinking "},
{ key:"ein Getränk/Getränk/die Getränke/Getränke ", value:" the drink"},
{ key:"trank ", value:" drank"},
{ key:"das Wasser/Wasser ", value:" the water "},
{ key:"das Ei/die Eier (pl) ", value:" the egg"},
{ key:"das Café/die Cafés (pl) ", value:" the cafeshop"},
{ key:"der Kaffee/Kaffee ", value:" the coffee drink"},
{ key:"Kaffeemaschine ", value:" the coffee machine"},
{ key:"die Milch/Milch ", value:" the milk "},
{ key:"das Bier/Bier ", value:" the beer"},
{ key:"groß/groß/große ", value:" big "},
{ key:"größer ", value:" bigger "},
{ key:"am größten ", value:" the biggest "},
{ key:"klein ", value:" small "},
{ key:"klein ", value:" small "},
{ key:"ein bisschen ", value:" a little "},
{ key:"wenig ", value:" little "},
{ key:"billig/billige ", value:" cheap "},
{ key:"billiger/billigere ", value:" cheaper "},
{ key:"am billigsten ", value:" the cheapest"},
{ key:"teuer/teuer/teure ", value:" expensive "},
{ key:"teurer ", value:" more expensive"},
{ key:"am teuersten ", value:" most expensive"},
{ key:"das Tier/die Tiere (pl) ", value:" the animal"},
{ key:"oft ", value:" often"},
{ key:"öfter ", value:" more often"},
{ key:"nie ", value:" never "},
{ key:"ab und zu ", value:" sometimes"},
{ key:"und ", value:" and"},
{ key:"oder ", value:" or"},
{ key:"weg ", value:" away, gone "},
{ key:"weit/weite/weit ", value:" far, long "},
{ key:"Deutschland ", value:" Germany"},
{ key:"deutsch ", value:" german "},
{ key:"Schweden ", value:" Sweden"},
{ key:"von/aus ", value:" from "},
{ key:"kommen ", value:" to come"},
{ key:"kam ", value:" came "},
{ key:"gekommen ", value:" come "},
{ key:"kommen zu ", value:" going to "},
{ key:"schwimmen/zu schwimmen ", value:" to swim"},
{ key:"geschwommen ", value:" swam "},
{ key:"schwamm ", value:" swam "},
{ key:"geschwommen ", value:" swam "},
{ key:"wohnen/zu wohnen ", value:" to live, stay "},
{ key:"gewohnt ", value:" lived "},
{ key:"wohnte ", value:" lived "},
{ key:"wissen/zu wissen ", value:" to know "},
{ key:"gewusst ", value:" known "},
{ key:"wusste ", value:" knew "},
{ key:"schreiben/zu schreiben ", value:" to write"},
{ key:"ausdrucken ", value:" to print"},
{ key:"schrieb ", value:" wrote "},
{ key:"geschrieben ", value:" wrote "},
{ key:"Drucker ", value:" the printers"},
{ key:"lesen/zu lesen ", value:" to read"},
{ key:"las ", value:" read "},
{ key:"gelesen ", value:" read "},
{ key:"lernen/zu lernen ", value:" to learn, teach "},
{ key:"gelernt ", value:" learned "},
{ key:"lernte ", value:" learned "},
{ key:"der Lehrer/die Lehrer (pl) ", value:" the teacher"},
{ key:"sprechen/zu sprechen ", value:" to speak "},
{ key:"sprach ", value:" spoke "},
{ key:"die Sprache/die Sprachen (pl) ", value:" the language"},
{ key:"verstehen/zu verstehen ", value:" to understand "},
{ key:"verstand ", value:" understood"},
{ key:"das Land/die Länder (pl) ", value:" the country"},
{ key:"das Dorf/die Dörfer (pl) ", value:" the village"},
{ key:"die Stadt/die Städte (pl) ", value:" the city"},
{ key:"der Tee/Tee ", value:" the tea"},
{ key:"die Katze/die Katzen (pl) ", value:" the cat"},
{ key:"der Hund/die Hunde (pl) ", value:" the dog"},
{ key:"das Brot/Brot ", value:" the bread"},
{ key:"der Bruder/die Brüder (pl) ", value:" the brother"},
{ key:"Brüder/Brüder ", value:" the brothers"},
{ key:"die Mutter/die Mütter (pl) ", value:" the mother "},
{ key:"Mütter/Mütter ", value:" the mothers"},
{ key:"der Vater/die Väter (pl) ", value:" the father"},
{ key:"Väter/Väter ", value:" the fathers"},
{ key:"der Sohn/die Söhne (pl) ", value:" the son"},
{ key:"die Schwester/die Schwestern (pl) ", value:" the sister"},
{ key:"das Geschwister/die Geschwister (pl) ", value:" the sibling"},
{ key:"die Tochter/die Töchter (pl) ", value:" the daughter "},
{ key:"Töchter/Töchter ", value:" the daughters"},
{ key:"der Junge/die Jungen (pl) ", value:" the boy"},
{ key:"die Frau/die Frauen (pl) ", value:" the woman"},
{ key:"Frauenkleidung ", value:" woman clothing"},
{ key:"der Mann/die Männer (pl) ", value:" the man, husband "},
{ key:"man ", value:" you (one)"},
{ key:"die Frau/die Frauen (pl) ", value:" the wife"},
{ key:"das Mädchen/die Mädchen (pl) ", value:" the girl "},
{ key:"wie geht's ", value:" how goes it"},
{ key:"es geht gut ", value:" it goes well"},
{ key:"geht's gut? ", value:" goes it well"},
{ key:"das ", value:" that "},
{ key:"guten Morgen ", value:" good morning"},
{ key:"guten Tag ", value:" good afternoon"},
{ key:"guten Abend ", value:" good evening"},
{ key:"der Morgen/die Morgen (pl) ", value:" the morning"},
{ key:"Morgen ", value:" mornings"},
{ key:"der Morgen ", value:" the morning"},
{ key:"der Abend/die Abende (pl) ", value:" the evening"},
{ key:"ich ", value:" I "},
{ key:"du ", value:" you"},
{ key:"er ", value:" he"},
{ key:"sie ", value:" she"},
{ key:"wir ", value:" we"},
{ key:"ihr ", value:" you"},
{ key:"sie ", value:" they, those "},
{ key:"mich ", value:" me"},
{ key:"anziehen ", value:" is wearing "},
{ key:"dich ", value:" you"},
{ key:"sich ", value:" itself "},
{ key:"ihn ", value:" him"},
{ key:"sie ", value:" her"},
{ key:"sie ", value:" them"},
{ key:"eure/ihre ", value:" yours, theirs"},
{ key:"uns ", value:" us"},
{ key:"mein/meine/mein ", value:" mine"},
{ key:"dein/deine/dein ", value:" yours"},
{ key:"sein ", value:" his"},
{ key:"ihr ", value:" hers"},
{ key:"sein/sein/seine ", value:" own's "},
{ key:"unser/unser/unsere ", value:" our "},
{ key:"eins/ein ", value:" one"},
{ key:"zwei ", value:" two"},
{ key:"drei ", value:" three"},
{ key:"vier ", value:" four"},
{ key:"fünf ", value:" five"},
{ key:"sechs ", value:" six"},
{ key:"sieben ", value:" seven"},
{ key:"acht ", value:" eight"},
{ key:"neun ", value:" nine"},
{ key:"zehn ", value:" ten"},
{ key:"elf ", value:" eleven"},
{ key:"zwölf ", value:" twelve"},
{ key:"dreizehn ", value:" thirteen"},
{ key:"vierzehn ", value:" fourteen"},
{ key:"fünfzehn ", value:" fifteen"},
{ key:"sechzehn ", value:" sixteen"},
{ key:"siebzehn ", value:" seventeen"},
{ key:"achtzehn ", value:" eighteen"},
{ key:"neunzehn ", value:" nineteen"},
{ key:"zwanzig ", value:" twenty"},
{ key:"dreißig ", value:" thirty"},
{ key:"vierzig ", value:" fourty"},
{ key:"fünfzig ", value:" fifty"},
{ key:"sechzig ", value:" sixty"},
{ key:"siebzig ", value:" seventy"},
{ key:"achtzig ", value:" eighty"},
{ key:"neunzig ", value:" ninety"},
{ key:"hundert ", value:" hundred"},
{ key:"tausend ", value:" thousand"},
{ key:"einundzwanzig ", value:" twentyone"},
{ key:"zweiundzwanzig ", value:" twentytwo"},
{ key:"dreiundzwanzig ", value:" twentythree"},
{ key:"vierundzwanzig ", value:" twentyfour"},
{ key:"fünfundzwanzig ", value:" twentyfive"},
{ key:"sechsundzwanzig ", value:" twentysix"},
{ key:"siebenundzwanzig ", value:" twentyseven"},
{ key:"achtundzwanzig ", value:" twentyeight"},
{ key:"neunundzwanzig ", value:" twentynine"},
{ key:"erste/zuerst ", value:" first"},
{ key:"zweite ", value:" second, other people"},
{ key:"der andere ", value:" the other"},
{ key:"dritte ", value:" third"},
{ key:"vierte ", value:" fourth"},
{ key:"fünfte ", value:" fifth"},
{ key:"sechste ", value:" sixth"},
{ key:"siebente ", value:" seventh"},
{ key:"achte ", value:" eighth"},
{ key:"neunte ", value:" ninth"},
{ key:"zehnte ", value:" tenth"},
{ key:"elfte ", value:" eleventh"},
{ key:"zwölfte ", value:" twelfth"},
{ key:"dreizehnte ", value:" thirteenth"},
{ key:"vierzehnte ", value:" fourteenth"},
{ key:"fünfzehnte ", value:" fifteenth"},
{ key:"sechzehnte ", value:" sixteenth"},
{ key:"siebzehnte ", value:" seventeenth"},
{ key:"achtzehnte ", value:" eightteenth"},
{ key:"neunzehnte ", value:" nineteenth"},
{ key:"Montag ", value:" Monday"},
{ key:"Dienstag ", value:" Tuesday"},
{ key:"Mittwoch ", value:" Wednesday"},
{ key:"Donnerstag ", value:" Thursday"},
{ key:"Freitag ", value:" Friday"},
{ key:"Samstag ", value:" Saturday"},
{ key:"Sonntag ", value:" Sunday"},
{ key:"der Samstag ", value:" the Saturday "},
{ key:"am Montag ", value:" mondays"},
{ key:"die Muttersprache/Muttersprache ", value:" the mothertongue"},
{ key:"der Bahnhof/die Bahnhöfe (pl) ", value:" the station"},
{ key:"die Bibliothek/die Bibliotheken (pl) ", value:" the library"},
{ key:"der Park/die Parks (pl) ", value:" the park"},
{ key:"die Kirche/die Kirchen (pl) ", value:" the church"},
{ key:"das Hotel/die Hotels (pl) ", value:" the hotel"},
{ key:"das Hotelzimmer/die Hotelzimmer (pl) ", value:" the hotel room"},
{ key:"das Museum/die Museen (pl) ", value:" the museum"},
{ key:"die Speisekarte/die Speisekarten (pl) ", value:" the menu"},
{ key:"der Freund/die Freunde (pl) ", value:" the friend"},
{ key:"freundlich/freundliche ", value:" friendly "},
{ key:"der Supermarkt/die Supermärkte (pl) ", value:" the grocery store"},
{ key:"der Laden/die Läden (pl) ", value:" the store"},
{ key:"das Kino/die Kinos (pl) ", value:" the cinema"},
{ key:"die Apotheke/die Apotheken (pl) ", value:" the pharmacy"},
{ key:"die Bäckerei/die Bäckereien (pl) ", value:" the bakery"},
{ key:"backen/zu backen ", value:" to bake"},
{ key:"Bäcker ", value:" a baker"},
{ key:"jung/jung/junge ", value:" young "},
{ key:"Jugend ", value:" the young "},
{ key:"jünger ", value:" younger"},
{ key:"alt/alt/alte ", value:" old "},
{ key:"älter ", value:" older"},
{ key:"neu/neue/neu ", value:" new"},
{ key:"neuer ", value:" newer"},
{ key:"neueste ", value:" newest"},
{ key:"der Geldautomat/die Geldautomaten (pl) ", value:" the ATM"},
{ key:"die Bank/die Banken (pl) ", value:" the bank "},
{ key:"Journalist ", value:" a journalist"},
{ key:"der Anwalt/die Anwälte (pl) ", value:" a lawyer"},
{ key:"die Universität/die Universitäten (pl) ", value:" the university"},
{ key:"Januar ", value:" January"},
{ key:"Februar ", value:" February"},
{ key:"März ", value:" Mars"},
{ key:"April ", value:" April"},
{ key:"Mai ", value:" May"},
{ key:"Juni ", value:" June"},
{ key:"Juli ", value:" July"},
{ key:"August ", value:" August"},
{ key:"September ", value:" September"},
{ key:"Oktober ", value:" Oktober"},
{ key:"November ", value:" November"},
{ key:"Dezember ", value:" December"},
{ key:"das Jahr/die Jahre (pl) ", value:" the year "},
{ key:"des Jahres ", value:" year`s"},
{ key:"die Woche/die Wochen (pl) ", value:" the week"},
{ key:"der Monat/die Monate (pl) ", value:" the month"},
{ key:"die Banane/die Bananen (pl) ", value:" the bannana"},
{ key:"der Apfel/die Äpfel (pl) ", value:" the apple"},
{ key:"der Salat/die Salate (pl) ", value:" the salad, letuce"},
{ key:"in ", value:" in "},
{ key:"für eine Stunde ", value:" for an hour "},
{ key:"in/innen ", value:" inside "},
{ key:"aus/außen ", value:" outside "},
{ key:"außerhalb ", value:" outside, outside of "},
{ key:"ausländisch ", value:" foreign "},
{ key:"ohne ", value:" without "},
{ key:"an/auf ", value:" at, on "},
{ key:"zu ", value:" to, of "},
{ key:"in Deutschland ", value:" in Germany"},
{ key:"heute ", value:" today"},
{ key:"gestern ", value:" yesterday "},
{ key:"vorgestern ", value:" day before yesterday"},
{ key:"heute Morgen ", value:" this morning"},
{ key:"morgen ", value:" tomorrow"},
{ key:"übermorgen ", value:" day after tomorrow"},
{ key:"dieses Jahr ", value:" this year"},
{ key:"letztes Jahr ", value:" last year "},
{ key:"in der Nähe ", value:" nearby"},
{ key:"nah/nah ", value:" near "},
{ key:"am nächsten ", value:" nearest"},
{ key:"die Zeit/Zeit ", value:" the time "},
{ key:"tun/zu tun ", value:" to do "},
{ key:"getan ", value:" done "},
{ key:"tat ", value:" did "},
{ key:"bei ", value:" at, with "},
{ key:"treffen/zu treffen ", value:" to meet "},
{ key:"das Treffen/die Treffen (pl) ", value:" the meeting"},
{ key:"traf ", value:" met "},
{ key:"getroffen ", value:" have met "},
{ key:"gegen ", value:" to, towards, against "},
{ key:"können ", value:" can "},
{ key:"stehen/zu stehen ", value:" to stand, stay "},
{ key:"stand ", value:" stood"},
{ key:"aufstehen/zu aufstehen ", value:" to get up, stand, wake"},
{ key:"bleiben ", value:" to stay, to become "},
{ key:"wurde ", value:" was"},
{ key:"geworden ", value:" been "},
{ key:"die Straße/die Straßen (pl) ", value:" the street "},
{ key:"schreien/zu schreien ", value:" to yell"},
{ key:"der Schrei/die Schreie (pl) ", value:" the scream"},
{ key:"halb ", value:" half "},
{ key:"Hälfte ", value:" half of"},
{ key:"Viertel ", value:" quarter"},
{ key:"reden/zu reden ", value:" to talk, chat "},
{ key:"redete ", value:" talked "},
{ key:"das Gespräch/die Gespräche (pl) ", value:" the chat"},
{ key:"vergessen/zu vergessen ", value:" to forget "},
{ key:"vergessen ", value:" forgotten "},
{ key:"vergaß ", value:" forgot"},
{ key:"erinnern/zu erinnern ", value:" to remember"},
{ key:"erinnerte ", value:" remembered "},
{ key:"versuchen ", value:" to try"},
{ key:"versuchte ", value:" tried"},
{ key:"die Prüfung/die Prüfungen (pl) ", value:" the test, exam"},
{ key:"das Keks/die Kekse (pl) ", value:" the cookie"},
{ key:"das Haustier/die Haustiere (pl) ", value:" the pet"},
{ key:"lieber ", value:" dear "},
{ key:"der Freund/Freund (pl) ", value:" the sweetheart, boyfriend, girlfriend"},
{ key:"Liebe ", value:" the love"},
{ key:"hübsch ", value:" handsome"},
{ key:"langweilig/langweilige ", value:" boring "},
{ key:"die Küche/die Küchen (pl) ", value:" the kitchen"},
{ key:"das Kleid/die Kleider (pl) ", value:" the dress"},
{ key:"der Kühlschrank/die Kühlschränke (pl) ", value:" the refrigerator"},
{ key:"kühlen ", value:" cool"},
{ key:"der Schrank/die Schränke (pl) ", value:" closet "},
{ key:"kaufen/zu kaufen ", value:" to buy "},
{ key:"das Einkaufszentrum/die Einkaufszentren (pl) ", value:" the shopping center, mall"},
{ key:"kaufte ", value:" bought "},
{ key:"fahren/zu fahren ", value:" to drive "},
{ key:"fuhr ", value:" drove"},
{ key:"Fahren ", value:" driving "},
{ key:"das Fleisch/Fleisch ", value:" the meat "},
{ key:"Kleidung/Kleidung/die Kleidungen/Kleidungen ", value:" clothes"},
{ key:"der Kleiderladen/die Kleiderläden (pl) ", value:" the clothing store"},
{ key:"anziehen ", value:" to get dressed "},
{ key:"gekleidet ", value:" dressed, clothed"},
{ key:"Riese ", value:" giant"},
{ key:"fantastisch ", value:" terrific"},
{ key:"wirklich schwer ", value:" really heavy "},
{ key:"riesig ", value:" really big"},
{ key:"wirklich warm ", value:" really warm"},
{ key:"wirklich lang ", value:" really long"},
{ key:"kennen/zu kennen ", value:" to know "},
{ key:"bekannt/bekannte ", value:" known "},
{ key:"unbekannt ", value:" unknown"},
{ key:"die Kette/die Ketten (pl) ", value:" the chain, necklace"},
{ key:"die Kraft/die Kräfte (pl) ", value:" the force, craft, power"},
{ key:"der Unfall/die Unfälle (pl) ", value:" the accident "},
{ key:"der Unfall/die Unfälle (pl) ", value:" the accident"},
{ key:"Schlange ", value:" river"},
{ key:"Sommerjob ", value:" summer job"},
{ key:"Telefonverkäufer ", value:" telemarketer"},
{ key:"Feuer ", value:" fire"},
{ key:"Feuerwehrleute/Feuerwehrleute ", value:" the firemen"},
{ key:"der Klempner/die Klempner (pl) ", value:" the plumber"},
{ key:"der Elektriker/die Elektriker (pl) ", value:" the electrician"},
{ key:"Überstunden ", value:" overtime"},
{ key:"Arbeitskleidung ", value:" workclothes"},
{ key:"Arbeitsumfeld ", value:" the working environment"},
{ key:"Indien ", value:" india"},
{ key:"griechisch/griechische ", value:" greek "},
{ key:"die Vorspeise/die Vorspeisen (pl) ", value:" the appetizer"},
{ key:"das Hauptgericht/die Hauptgerichte (pl) ", value:" the main course"},
{ key:"Lieferservice ", value:" the delivery service"},
{ key:"anbieten/zu anbieten ", value:" to offer"},
{ key:"bot an ", value:" offered"},
{ key:"der Teller/die Teller (pl) ", value:" the plate"},
{ key:"die Bohne/die Bohnen (pl) ", value:" the bean"},
{ key:"Kaffeebohnen ", value:" coffee beans"},
{ key:"die Mahlzeit/die Mahlzeiten (pl) ", value:" the meal"},
{ key:"servieren ", value:" to serve"},
{ key:"sauer ", value:" sour"},
{ key:"der Lachs/die Lachse (pl) ", value:" the salmon"},
{ key:"Hausnummer ", value:" the house number"},
{ key:"Postleitzahl ", value:" the zip code"},
{ key:"Butter ", value:" butter"},
{ key:"Knoblauch ", value:" garlik"},
{ key:"Zwiebel ", value:" red onion"},
{ key:"das Öl/Öl ", value:" the oil"},
{ key:"Trinkgeld ", value:" the tip "},
{ key:"Kleingeld ", value:" change"},
{ key:"Essig ", value:" vinegar"},
{ key:"Reisessig ", value:" rice vinegar"},
{ key:"das Gerücht/die Gerüchte (pl) ", value:" the rumor"},
{ key:"tratschen/zu tratschen ", value:" to gossip"},
{ key:"lügen/zu lügen ", value:" to lie, lying"},
{ key:"log ", value:" lied "},
{ key:"das Gespenst/die Gespenster (pl) ", value:" ghost"},
{ key:"heimgesucht ", value:" haunted"},
{ key:"böse/böse ", value:" evil"},
{ key:"neugierig ", value:" curious "},
{ key:"die Hexe/die Hexen (pl) ", value:" witch"},
{ key:"das Monster/die Monster (pl) ", value:" the monster"},
{ key:"fühlen/zu fühlen ", value:" to feel"},
{ key:"gefühlt ", value:" felt"},
{ key:"das Gefühl/die Gefühle (pl) ", value:" feeling"},
{ key:"der Fjord/die Fjorde (pl) ", value:" fjord"},
{ key:"die Vorspeise/die Vorspeisen (pl) ", value:" the appetizer"},
{ key:"heimgesucht ", value:" haunted"},
{ key:"Studentenwohnheim ", value:" student village"},
{ key:"Kleiderbügel/Kleiderbügel ", value:" clothes hangers"},
{ key:"aufhalten/zu aufhalten ", value:" to reside, occupy "},
{ key:"Campus ", value:" the campus"},
{ key:"international ", value:" international"},
{ key:"das Laken/die Laken (pl) ", value:" the sheet"},
{ key:"neben ", value:" next to"},
{ key:"der Ventilator/die Ventilatoren (pl) ", value:" the fan"},
{ key:"die Wand/die Wände (pl) ", value:" the wall"},
{ key:"der Mülleimer/die Mülleimer (pl) ", value:" the trash can"},
{ key:"der Vorhang/die Vorhänge (pl) ", value:" the curtain"},
{ key:"das Ladegerät/die Ladegeräte (pl) ", value:" the charger"},
{ key:"Wasserkocher ", value:" water boiler"},
{ key:"lachen/zu lachen ", value:" to laugh"},
{ key:"lachte ", value:" laughed"},
{ key:"verliebt ", value:" in love "},
{ key:"der Himmel/Himmel ", value:" the heaven "},
{ key:"Menschen ", value:" people"},
{ key:"einsam/einsame ", value:" lonely "},
{ key:"deprimiert ", value:" depressed"},
{ key:"das Herz/die Herzen (pl) ", value:" the heart"},
{ key:"bitter/bitter ", value:" bitter "},
{ key:"stolz/stolze ", value:" proud "},
{ key:"normal ", value:" normal"},
{ key:"beschweren/zu beschweren ", value:" to complain"},
{ key:"genau ", value:" exactly"},
{ key:"das Klavier/Klavier ", value:" the piano"},
{ key:"die Brücke/die Brücken (pl) ", value:" the bridge"},
{ key:"die Muschel/die Muscheln (pl) ", value:" the shell"},
{ key:"der Weg/die Wege (pl) ", value:" the way "},
{ key:"die Schlange/die Schlangen (pl) ", value:" the queue"},
{ key:"der Hügel/die Hügel (pl) ", value:" the hill"},
{ key:"winken ", value:" to wave"},
{ key:"der Bikini/die Bikinis (pl) ", value:" the bikini"},
{ key:"haupt ", value:" main "},
{ key:"Stadt ", value:" a city"},
{ key:"die Hauptstadt/Hauptstadt ", value:" the capital city"},
{ key:"überqueren/zu überqueren ", value:" to cross"},
{ key:"nicht überqueren! ", value:" don't cross"},
{ key:"überquerte ", value:" crossed"},
{ key:"Kultur ", value:" the culture"},
{ key:"die Dame/die Damen (pl) ", value:" the lady"},
{ key:"der Herr/die Herren (pl) ", value:" the gentleman"},
{ key:"landen/zu landen ", value:" to land"},
{ key:"die Sanduhr/Sanduhr ", value:" the hourglass"},
{ key:"normal ", value:" normal"},
{ key:"bedeutend ", value:" significant "},
{ key:"betrachten ", value:" to consider"},
{ key:"großzügig ", value:" generous"},
{ key:"vernünftig ", value:" reasonable, fair"},
{ key:"der Anteil/die Anteile (pl) ", value:" the share "},
{ key:"die Bedrohung/die Bedrohungen (pl) ", value:" the threat "},
{ key:"eiskalt ", value:" freezing"},
{ key:"stricken/zu stricken ", value:" to knit"},
{ key:"das Video/die Videos (pl) ", value:" the video"},
{ key:"der Schal/die Schals (pl) ", value:" the scarf"},
{ key:"das Omelett/die Omeletts (pl) ", value:" the omelet"},
{ key:"Telefonverkäufer ", value:" telemarketer"},
{ key:"die SMS/die SMS (pl) ", value:" the text message"},
{ key:"das Spa/die Spas (pl) ", value:" spa"},
{ key:"Snowboard fahren ", value:" to snowboard"},
{ key:"eiskalt ", value:" freezing"},
{ key:"das Alphabet/Alphabet ", value:" the alphabet"},
{ key:"Buchstaben/Buchstaben ", value:" the letter"},
{ key:"buchstabieren/zu buchstabieren ", value:" to spell"},
{ key:"der Handschuh/die Handschuhe (pl) ", value:" the glove"},
{ key:"Toast ", value:" toast"},
{ key:"die Ski/die Skier (pl) ", value:" the skis"},
{ key:"Ski fahren ", value:" go skiing"},
{ key:"Schneemann ", value:" the snowman"},
{ key:"schlittschuhlaufen ", value:" to skate "},
{ key:"Winterstiefel/Winterstiefel ", value:" the winterboots"},
{ key:"der Schüler/die Schüler (pl) ", value:" the student"},
{ key:"Studentenausweis ", value:" the student card"},
{ key:"Schuluniform ", value:" the school uniform"},
{ key:"Uniform ", value:" the uniform"},
{ key:"der Satz/die Sätze (pl) ", value:" statement, sentence"},
{ key:"das Klassenzimmer/die Klassenzimmer (pl) ", value:" the classroom"},
{ key:"verstehen/zu verstehen ", value:" to see, to understand "},
{ key:"außer ", value:" except, but"},
{ key:"die Tafel/die Tafeln (pl) ", value:" the board "},
{ key:"die Klasse/die Klassen (pl) ", value:" the class"},
{ key:"das Fragezeichen/Fragezeichen ", value:" the questionmark"},
{ key:"mobbing ", value:" bullied "},
{ key:"konzentrieren ", value:" to consentrate "},
{ key:"der Schulhof/die Schulhöfe (pl) ", value:" the schoolyard"},
{ key:"Geographiestunde ", value:" the geography class"},
{ key:"schaffen/zu schaffen ", value:" to manage, be able "},
{ key:"zur Ruhe kommen ", value:" calmed down"},
{ key:"Rabatt ", value:" discount"},
{ key:"spannend ", value:" exciting"},
{ key:"Rentner ", value:" rediree"},
{ key:"außerdem ", value:" besides"},
{ key:"Platz ", value:" squares, plazzas"},
{ key:"ein Klassiker ", value:" a classic"},
{ key:"Untertitel ", value:" subtitles"},
{ key:"eilen ", value:" hurry"},
{ key:"der Ausgang/die Ausgänge (pl) ", value:" the exit"},
{ key:"psst ", value:" hush!, shush!"},
{ key:"verpassen ", value:" to miss"},
{ key:"Reihe ", value:" row "},
{ key:"folgen/zu folgen ", value:" to follow "},
{ key:"Schock ", value:" shock"},
{ key:"geschockt ", value:" shocked"},
{ key:"schockierend ", value:" shockingly"},
{ key:"Prüfung ", value:" the exam"},
{ key:"wenden/zu wenden ", value:" to turn "},
{ key:"wandte ", value:" turned "},
{ key:"verschieden/verschiedene ", value:" different, dissimilar"},
{ key:"der Magen/Magen ", value:" the stomach"},
{ key:"enthüllen/zu enthüllen ", value:" to expose, reveal"},
{ key:"enthüllte ", value:" exposed"},
{ key:"Rest ", value:" the rest"},
{ key:"laut ", value:" according to"},
{ key:"durchsickern/zu durchsickern ", value:" to leak"},
{ key:"durchgesickert ", value:" leaked"},
{ key:"die Regierung/die Regierungen (pl) ", value:" the government"},
{ key:"das Budget/die Budgets (pl) ", value:" the budget"},
{ key:"anziehen/zu anziehen ", value:" to tighten "},
{ key:"gelten/zu gelten ", value:" to apply"},
{ key:"zugeben ", value:" to admit"},
{ key:"der Missbrauch/die Missbräuche (pl) ", value:" abuse"},
{ key:"das Opfer/die Opfer (pl) ", value:" the victim"},
{ key:"der Rat/die Räte (pl) ", value:" the advice"},
{ key:"Austauschstudent ", value:" exchange student"},
{ key:"wahnsinnig ", value:" insanely"},
{ key:"trotz ", value:" despite"},
{ key:"die Brust/die Brüste (pl) ", value:" chest "},
{ key:"Vorbereitungen ", value:" preparations"},
{ key:"wie ", value:" like"},
{ key:"Beispiel ", value:" example, zum Beispiel -- such as"},
{ key:"deshalb ", value:" therefore"},
{ key:"Ausländer ", value:" foreigner"},
{ key:"kümmern ", value:" care "},
{ key:"gegen ", value:" against "},
{ key:"die Übersetzung/die Übersetzungen (pl) ", value:" translation"},
{ key:"Gespräch ", value:" conversation "},
{ key:"verfügbar ", value:" available "},
{ key:"Hölle ", value:" hell"},
{ key:"mein Gott ", value:" oh my god"},
{ key:"der Schwarze Tod ", value:" the black death (plague)"},
{ key:"die Bevölkerung/Bevölkerung ", value:" population"},
{ key:"wüten ", value:" reign"},
{ key:"Gesetzlosigkeit ", value:" lawlessness"},
{ key:"verlassen ", value:" desolate"},
{ key:"Kerl ", value:" fellow"},
{ key:"abhängen ", value:" depends"},
{ key:"empfohlen ", value:" reccomended"},
{ key:"schnell ", value:" quick "},
{ key:"schnell ", value:" quickly"},
{ key:"meinen/zu meinen ", value:" to mean, think "},
{ key:"auffüllen ", value:" to refill"},
{ key:"Nachfüllung ", value:" refill "},
{ key:"anderes ", value:" other "},
{ key:"Zahl ", value:" number"},
{ key:"verdammt ", value:" damn"},
{ key:"die Aufgabe/die Aufgaben (pl) ", value:" task"},
{ key:"Masterarbeit ", value:" the master thesis"},
{ key:"Premierminister ", value:" prime minister"},
{ key:"die Beziehung/die Beziehungen (pl) ", value:" relationship"},
{ key:"Schweigen ", value:" the silence "},
{ key:"legen ", value:" to lay"},
{ key:"die Sache/die Sachen (pl) ", value:" the case, matter"},
{ key:"überrascht ", value:" surprised"},
{ key:"umfangreich ", value:" extensive"},
{ key:"das Gesetz/die Gesetze (pl) ", value:" the law "},
{ key:"versprechen/zu versprechen ", value:" to vow"},
{ key:"Betrug ", value:" cheating"},
{ key:"Betrug ", value:" cheating"},
{ key:"verdächtigt ", value:" suspected"},
{ key:"erleben ", value:" to experience "},
{ key:"ausgeschlossen ", value:" be banned"},
{ key:"Ausbildung ", value:" education "},
{ key:"Rache ", value:" revenge"},
{ key:"vorstellen ", value:" to represent "},
{ key:"sich vorstellen ", value:" to imagine"},
{ key:"träumen ", value:" to dream"},
{ key:"geträumt ", value:" dreamt"},
{ key:"nun ", value:" well "},
{ key:"Osten ", value:" east"},
{ key:"Westen ", value:" west"},
{ key:"Norden ", value:" north "},
{ key:"Süden ", value:" south"},
{ key:"genießen ", value:" enjoy"},
{ key:"obwohl ", value:" even though, although"},
{ key:"gießen ", value:" heels (?), es gießt -- pile down (accumulate)"},
{ key:"sterben ", value:" to die "},
{ key:"ausschalten/zu ausschalten ", value:" to turn, to turn back"},
{ key:"ausschalten ", value:" to turn off "},
{ key:"schlagen ", value:" to beat"},
{ key:"nachschlagen ", value:" to look up "},
{ key:"vorschlagen ", value:" to propose"},
{ key:"ausschalten ", value:" turn off"},
{ key:"nachschlagen/nachschlagen ", value:" look up "},
{ key:"der Glaube/Glaube ", value:" the faith "},
{ key:"zweifeln/zu zweifeln ", value:" to doubt "},
{ key:"zweifelte ", value:" doubted"},
{ key:"vertrauen/zu vertrauen ", value:" to trust"},
{ key:"verletzen ", value:" to hurt, wound "},
{ key:"verletzt ", value:" hurt, wounded"},
{ key:"Geheimnis ", value:" secret"},
{ key:"geheim ", value:" secret"},
{ key:"stimmen ", value:" votes "},
{ key:"die Patrouille/die Patrouillen (pl) ", value:" patrol, police"},
{ key:"unwahrscheinlich ", value:" unlikely"},
{ key:"entführt ", value:" abducted"},
{ key:"hörbar ", value:" audible"},
{ key:"unhörbar ", value:" inaudible"},
{ key:"Dialog ", value:" dialog"},
{ key:"fordern ", value:" to request"},
{ key:"ausgeliefert ", value:" released, out delivered"},
{ key:"liefern ", value:" to deliver "},
{ key:"geliefert ", value:" delivered"},
{ key:"schnauben ", value:" to snort"},
{ key:"untersuchen ", value:" to investigate"},
{ key:"die Freiheit/Freiheit ", value:" the freedom "},
{ key:"vor ", value:" before, over"},
{ key:"die Verantwortung/Verantwortung ", value:" responsability"},
{ key:"Risiko ", value:" risk"},
{ key:"real ", value:" real"},
{ key:"schützen ", value:" to protect"},
{ key:"Schützer ", value:" guardian"},
{ key:"aufwachen ", value:" to wake up"},
{ key:"wachte auf ", value:" woke"},
{ key:"die Ziele/Ziele ", value:" goals"},
{ key:"erreichen/zu erreichen ", value:" to reach "},
{ key:"Kartoffeln ", value:" potatoes"},
{ key:"Karotten ", value:" carrots"},
{ key:"das Kaninchen/die Kaninchen (pl) ", value:" the rabbit"},
{ key:"enttäuscht ", value:" dissapointed"},
{ key:"plötzlich ", value:" suddenly"},
{ key:"der Zettel/die Zettel (pl) ", value:" the note"},
{ key:"suchen/zu suchen ", value:" to seek"},
{ key:"einsam ", value:" lonely"},
{ key:"der Papagei/die Papageien (pl) ", value:" the parrot"},
{ key:"Freundschaft ", value:" friendship"},
{ key:"eingeladen ", value:" invited "},
{ key:"lud ein ", value:" invited "},
{ key:"drücken ", value:" to press"},
{ key:"Klingel ", value:" doorbell"},
{ key:"klopfen ", value:" to caress "},
{ key:"lächeln ", value:" to smile"},
{ key:"die Mütze/die Mützen (pl) ", value:" the hat"},
{ key:"Handschuhe ", value:" the mittens, gloves"},
{ key:"das Gras/Gras ", value:" the grass"},
{ key:"kitzeln ", value:" to tickle "},
{ key:"Wolle ", value:" wool "},
{ key:"die Haut/Haut ", value:" the skin "},
{ key:"glücklich ", value:" fortunate"},
{ key:"herrlich ", value:" beautiful"},
{ key:"das Vergnügen/Vergnügen ", value:" the pleasure "},
{ key:"die Leidenschaft/die Leidenschaften (pl) ", value:" the passion"},
{ key:"wahrscheinlich ", value:" belieaveable"},
{ key:"unglaublich ", value:" unbeliaveable"},
{ key:"kompliziert ", value:" complicated"},
{ key:"unkompliziert ", value:" uncomplicated"},
{ key:"neben ", value:" next to"},
{ key:"das Meer/die Meere (pl) ", value:" the sea"},
{ key:"das Meer/Meer ", value:" the sea"},
{ key:"der Vorteil/die Vorteile (pl) ", value:" the advantage"},
{ key:"umgeben ", value:" surrounded"},
{ key:"passieren ", value:" to pass"},
{ key:"das Studium/die Studien (pl) ", value:" the study"},
{ key:"beschäftigt ", value:" busy "},
{ key:"bestanden ", value:" passed (the classes)"},
{ key:"obendrein ", value:" furthermore"},
{ key:"seltsam ", value:" strange"},
{ key:"entspannen ", value:" to relax "},
{ key:"Ski fahren ", value:" to go skiing"},
{ key:"hängen ", value:" to hang"},
{ key:"gehängt ", value:" hung "},
{ key:"decken ", value:" to prepare "},
{ key:"saugen ", value:" to suck "},
{ key:"staubsaugen ", value:" to vacuum "},
{ key:"Geschirr spülen ", value:" dishes "},
{ key:"abtrocknen ", value:" remove "},
{ key:"Messer ", value:" knife"},
{ key:"erstochen ", value:" knifestabbed"},
{ key:"die Präposition/die Präpositionen (pl) ", value:" preposition"},
{ key:"Sommerfest ", value:" the summer fest"},
{ key:"mysteriös ", value:" mysterious"},
{ key:"Mitte ", value:" middle "},
{ key:"zwingen ", value:" coerced "},
{ key:"Forschung ", value:" research"},
{ key:"erzählen ", value:" tell"},
{ key:"erzählte ", value:" told"},
{ key:"genannt ", value:" called "},
{ key:"klar ", value:" clear"},
{ key:"klar ", value:" clearly "},
{ key:"Webseiten ", value:" websites"},
{ key:"Orte ", value:" places"},
{ key:"Information ", value:" information"},
{ key:"verpassen ", value:" miss "},
{ key:"spektakulär ", value:" spectacular"},
{ key:"ähneln ", value:" to resemble "},
{ key:"ähnelte ", value:" resembled "},
{ key:"so ", value:" such"},
{ key:"geschafft ", value:" was able to do"},
{ key:"erklären ", value:" to explain "},
{ key:"erklärte ", value:" explained "},
{ key:"erklärt ", value:" explained "},
{ key:"verdient ", value:" did deserve"},
{ key:"handelte von ", value:" was about"},
{ key:"das Chaos/Chaos ", value:" the mess "},
{ key:"der Zeitpunkt/die Zeitpunkte (pl) ", value:" the moment "},
{ key:"eilen ", value:" hurried"},
{ key:"Hunderte ", value:" hundreds"},
{ key:"Tausende ", value:" thousands"},
{ key:"Reihe ", value:" row "},
{ key:"der Moment/die Momente (pl) ", value:" the moment"},
{ key:"eine Weile ", value:" for a while"},
{ key:"der Akzent/die Akzente (pl) ", value:" the accent"},
{ key:"Schade ", value:" pitty "},
{ key:"vermeiden ", value:" avoid "},
{ key:"die Hitze/Hitze ", value:" the heat "},
{ key:"berühmt/berühmte ", value:" famous"},
{ key:"Schwimmbrille ", value:" swimming goggles"},
{ key:"wasserdicht ", value:" waterproof"},
{ key:"Chance ", value:" chance "},
{ key:"ertragen/zu ertragen ", value:" to withstand"},
{ key:"atmen ", value:" to breathe"},
{ key:"schwanger ", value:" pregnant"},
{ key:"Braut ", value:" bride"},
{ key:"Bräutigam ", value:" groom"},
{ key:"Fragebogen ", value:" questionnaire"},
{ key:"entdecken ", value:" to discover"},
{ key:"entdeckte ", value:" discovered"},
{ key:"eigen ", value:" own"},
{ key:"Gefängnis ", value:" prison"},
{ key:"eingestellt ", value:" was closed"},
{ key:"Wanderer ", value:" hikers"},
{ key:"umkommen ", value:" perished, died"},
{ key:"Unfall ", value:" accident"},
{ key:"Pfad ", value:" path"},
{ key:"fahren ", value:" to drive"},
{ key:"falsch ", value:" wrong"},
{ key:"Einstellung ", value:" settig"},
{ key:"altern ", value:" to age"},
{ key:"Weltraumrennen ", value:" space race"},
{ key:"das Rennen/die Rennen (pl) ", value:" race"},
{ key:"im Laufe von ", value:" in the course of "},
{ key:"Herbststurm ", value:" autumn storm"},
{ key:"Rahmen ", value:" frame"},
{ key:"explodieren ", value:" to explode "},
{ key:"eng ", value:" tight"},
{ key:"schwingen ", value:" swings "},
{ key:"wild ", value:" wild "},
{ key:"wild ", value:" wild "},
{ key:"beunruhigend ", value:" disturbing"},
{ key:"Zahlen ", value:" numbers"},
{ key:"Schulschwänzen ", value:" truancy "},
{ key:"verrückt ", value:" crazy"},
{ key:"Geisel ", value:" hostage"},
{ key:"lebensgefährlich ", value:" deadly"},
{ key:"künstliche Intelligenz ", value:" artificial intelligence"},
{ key:"reguliert werden ", value:" be regulated"},
{ key:"die Vereinbarung/die Vereinbarungen (pl) ", value:" the agreement, deal, appointment"},
{ key:"Sieg ", value:" victory"},
{ key:"der Sieg/die Siege (pl) ", value:" victory"},
{ key:"der Oberschenkel/die Oberschenkel (pl) ", value:" thigh"},
{ key:"Schande ", value:" shame"},
{ key:"gebogen ", value:" past, bent"},
{ key:"Wolken ", value:" clouds"},
{ key:"scheiß ", value:" crappy"},
{ key:"die Ziege/die Ziegen (pl) ", value:" the goat"},
{ key:"Brei ", value:" porrige"},
{ key:"instabil ", value:" unstable"},
{ key:"Abstand ", value:" distant"},
{ key:"gemütlich ", value:" nice"},
{ key:"genießen ", value:" to enjoy "},
{ key:"anderer ", value:" another, different"},
{ key:"die Gesellschaft/die Gesellschaften (pl) ", value:" the society"},
{ key:"Herzog ", value:" duke "},
{ key:"vermuten ", value:" to guess, assume"},
{ key:"verhandeln ", value:" to negotiate "},
{ key:"herausfordernd ", value:" challenging"},
{ key:"ahnen ", value:" to sense"},
{ key:"keinesfalls ", value:" absolutely not"},
{ key:"aufnehmen ", value:" to take in "},
{ key:"eine Mitfahrgelegenheit ", value:" a ride "},
{ key:"spazieren ", value:" to walk "},
{ key:"Gnade ", value:" grace "},
{ key:"geschickt ", value:" proficient, clever "},
{ key:"Sache ", value:" business "},
{ key:"der Fuchs/die Füchse (pl) ", value:" the fox"},
{ key:"fragen/zu fragen ", value:" to wonder, deceive "},
{ key:"fragte ", value:" wondered, deceived "},
{ key:"getäuscht ", value:" deceived "},
{ key:"halt die Klappe ", value:" shut up"},
{ key:"die Klemme/Klemme ", value:" the predicament"},
{ key:"Geschäft ", value:" business"},
{ key:"die Wurzel/die Wurzeln (pl) ", value:" the root"},
{ key:"geschlagen ", value:" struck "},
{ key:"eine Reihe von Gründen ", value:" a number of reasons"},
{ key:"ein Arschloch/Arschloch/die Arschlöcher/Arschlöcher ", value:" the bastard"},
{ key:"schnell ", value:" quickly"},
{ key:"mit Geschwindigkeit ", value:" with speed"},
{ key:"die Geschwindigkeit/Geschwindigkeit ", value:" the speed "},
{ key:"sorgen ", value:" to worry"},
{ key:"die Wirtschaft/Wirtschaft ", value:" the economy"},
{ key:"spielen/zu spielen ", value:" to play"},
{ key:"Meisterwerk ", value:" masterpiece "},
{ key:"Krieg ", value:" war"},
{ key:"Waffe ", value:" weapon"},
{ key:"Waffenstillstand ", value:" the cease fire"},
{ key:"Realität ", value:" the reality"},
{ key:"erreichen ", value:" to achieve"},
{ key:"fürchten ", value:" fear"},
{ key:"Angriff ", value:" attack"},
{ key:"Strafe ", value:" sentence, penalty "},
{ key:"gegen ", value:" opposition"},
{ key:"Zeuge ", value:" witness"},
{ key:"Strom ", value:" electricity, power"},
{ key:"nach Hause ", value:" home"},
{ key:"zwischen ", value:" between"},
{ key:"versorgen ", value:" to supply"},
{ key:"der Dieb/die Diebe (pl) ", value:" thief"},
{ key:"Entwicklung ", value:" development"},
{ key:"toben ", value:" to rage"},
{ key:"Windenergie ", value:" the wind power"},
{ key:"Gerichtsverfahren ", value:" the trial "},
{ key:"der Mitbewohner/die Mitbewohner (pl) ", value:" the roommate"},
{ key:"der Hals/die Hälse (pl) ", value:" the neck"},
{ key:"Freisetzung ", value:" release"},
{ key:"fortsetzen ", value:" continues"},
{ key:"die Grenze/die Grenzen (pl) ", value:" border"},
{ key:"der Schlag/die Schläge (pl) ", value:" the blow "},
{ key:"verboten ", value:" forbidden, banned"},
{ key:"der Staat/die Staaten (pl) ", value:" the state"},
{ key:"vernichtend ", value:" crushing"},
{ key:"Lastwagen ", value:" truck"},
{ key:"beschlagnahmen ", value:" seized"},
{ key:"gestohlen ", value:" stolen "},
{ key:"die Fähigkeit/die Fähigkeiten (pl) ", value:" the ability"},
{ key:"fokussieren/zu fokussieren ", value:" to focus"},
{ key:"süchtig ", value:" addicted"},
{ key:"Krämpfe ", value:" cramps"},
{ key:"Vorschlag ", value:" proposal"},
{ key:"Lawine ", value:" avalanche"},
{ key:"blockieren ", value:" to block"},
{ key:"der Feiertag/die Feiertage (pl) ", value:" the holiday"},
{ key:"Entführung ", value:" abduction"},
{ key:"Kinderheim ", value:" childrens home"},
{ key:"gerettet ", value:" saved"},
{ key:"funktionieren ", value:" to work "},
{ key:"eilen ", value:" to hasten"},
{ key:"haben gekämpft ", value:" have fought"},
{ key:"in Schwierigkeiten geraten ", value:" get into trouble"},
{ key:"Schwierigkeiten ", value:" difficulties"},
{ key:"starren ", value:" glared"},
{ key:"aussehen ", value:" looked "},
{ key:"ziehen ", value:" pulled"},
{ key:"die Sommersprossen/Sommersprossen ", value:" the freckles"},
{ key:"schneiden/zu schneiden ", value:" to cut"},
{ key:"urteilen/zu urteilen ", value:" to sentence, convict"},
{ key:"verurteilt ", value:" sentenced, convicted"},
{ key:"Gefängnis ", value:" prison"},
{ key:"Gleichstellungsgesetz ", value:" gender equality law"},
{ key:"erschossen ", value:" shot"},
{ key:"die Sporthalle/die Sporthallen (pl) ", value:" the sports center"},
{ key:"Sport ", value:" physical activity"},
{ key:"Bande ", value:" gang, criminal group"},
{ key:"angeklagt ", value:" charged "},
{ key:"kriminell ", value:" criminal"},
{ key:"der Verteidiger/die Verteidiger (pl) ", value:" defense attorney"},
{ key:"die Anzahl/Anzahl ", value:" the number, quantity"},
{ key:"klagen ", value:" to sue"},
{ key:"untersuchen ", value:" to investigate"},
{ key:"Verdächtiger ", value:" suspect"},
{ key:"Aufruhr ", value:" stir, fuss, commotion"},
{ key:"Aufruhr ", value:" uproar"},
{ key:"ändern ", value:" to change, modify"},
{ key:"Rückgang ", value:" decline"},
{ key:"Wachstum ", value:" growth"},
{ key:"Gespräche ", value:" conversations"},
{ key:"Gewalt ", value:" violence"},
{ key:"verweigern ", value:" deny"},
{ key:"Zugang ", value:" entry, access"},
{ key:"freigelassen werden ", value:" is released"},
{ key:"Verachtung ", value:" contempt"},
{ key:"Kapuzenpullover ", value:" hoodie"},
{ key:"auslösen ", value:" trigger"},
{ key:"verletzt ", value:" injured"},
{ key:"Explosion ", value:" explosion"},
{ key:"gewarnt ", value:" warned"},
{ key:"verwüstet ", value:" devastated"},
{ key:"geboren ", value:" borne"},
{ key:"unterbrochen ", value:" interrupted"},
{ key:"der Albtraum/die Albträume (pl) ", value:" the nightmare"},
{ key:"die Strafe/die Strafen (pl) ", value:" the penalty"},
{ key:"Teenager ", value:" teenager"},
{ key:"Minderjähriger ", value:" minor child"},
{ key:"die Niederlage/die Niederlagen (pl) ", value:" the defeat"},
{ key:"wichtig ", value:" important"},
];
